# Edit utils
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'Yggdroot/indentLine'
on_cmd = ['IndentLinesToggle']
hook_add = '''
  let g:loaded_indentLine = 1
  nmap <Space>i <C-u>:IndentLinesToggle<CR>
'''


# Programing utils
[[plugins]]
repo = 'tyru/caw.vim'
on_map = ['<Plug>(caw:hatpos:toggle)', '<Plug>(caw:zeropos:toggle)']

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']
on_ft = ['python']
hook_source = '''
  source $XDG_CONFIG_HOME/nvim/rc/plugins/vimquickrun.rc.vim
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python', 'javascript', 'html', 'css', 'markdown', 'make', 'vim']
hook_source = '''
  source $XDG_CONFIG_HOME/nvim/rc/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
on_ft = ['python']
hook_source = '''
  let g:gen_tags#ctags_auto_gen = 1
  let g:gen_tags#gtags_auto_gen = 0
'''

[[plugins]]
repo = 'janko-m/vim-test'
depends = ['vim-dispatch']
hook_source = '''
  let g:test:strategy = 'dispatch'
'''

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarTogglek']

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']


# Fuzzy Finder
[[plugins]]
repo = 'junegunn/fzf'
bulid = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
on_cmd = [
  'Files',
  'GFiles?',
  'Tags',
]


# Other utils
[[plugins]]
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
on_ft = ['markdown']

[[plugins]]
repo = 'Shougo/vimproc.vim'
bulid = 'make'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']
on_map = ['<plug>NERDTreeToggle', '<plug>NERDTreeTabsFind']
depends = ['nerdtree-git-plugin', 'vim-nerdtree-tabs']
hook_add = '''
  let NERDTreeShowHidden=1
  let NERDTreeIgnore=['\.pyc$', '__pycache__']
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
  let g:nerdtree_tabs_autofind = 0
  nmap <Space>f <plug>NERDTreeTabsToggle<CR>
  nmap <Space>t <plug>NERDTreeTabsFind<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = [
  'Git',
  'Gcommit',
  'Gstatus',
  'Gdiff',
  'Gblame',
  'Glog'
]

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = ['<Plug>(openbrowser-smart-search)']
hook_add = '''
  let g:netrw_nogx = 1
'''


# Syntax
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  let g:markdown_syntax_conceal = 0
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_source = '''
  let g:vim_json_syntax_conceal = 0
  let g:indentLine_noConcealCursor = ""
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = ['markdown', 'toml', 'help']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
