#:schema https://developers.openai.com/codex/config-schema.json
personality = "pragmatic"
approval_policy = "on-failure"
sandbox_mode = "workspace-write"
profile = "quick"

[tui]
animations = false
[notice.model_migrations]
"gpt-5.1-codex-mini" = "gpt-5.3-codex"

[features]
unified_exec = true
shell_snapshot = true

[profiles.deep]
model = "gpt-5.3-codex"
approval_policy = "on-request"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"

[profiles.quick]
model = "gpt-5.1-codex-mini"
model_reasoning_effort = "low"
