[settings]
experimental = true
pipx_uvx = true

[tools]
bun = "latest"
deno = "latest"
go = "latest"
node = "22.12.0"
python = "3.13.0"
rust = "latest"

java = "corretto-21.0.4.7.1"

"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:golang.org/x/tools/gopls" = "latest"

"npm:@biomejs/biome" = "latest"
"npm:pyright" = "latest"
"npm:typescript-language-server" = "latest"
"npm:yaml-language-server" = "latest"

"pipx:ruff" = "latest"
"pipx:ruff-lsp" = "latest"
"pipx:snowflake-cli" = "latest"

"cargo:sheldon" = "latest"

1password-cli = "latest"
awscli = "latest"
aws-vault = "latest"
bat = "latest"
buf = "latest"
cargo-binstall = "latest"
delta = "latest"
dust = "latest"
editorconfig-checker = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
ghq = "latest"
gradle = "latest"
grpcurl = "latest"
jnv = "latest"
jq = "latest"
neovim = "latest"
protoc = "latest"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
terraform-ls = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"
