[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[tools]
bun = "1.3.3"
deno = "2.5.6"
go = "1.25.5"
java = "corretto-25"
node = "lts"
python = "3.14.1"
rust = "1.91.1"

1password-cli = "2.31.1"
aqua = "2.50.0"
awscli = "2.32.9"
gcloud = "520.0.0"
gradle = "8.14"
protoc = "33.1"
shellcheck = "0.11.0"

"aqua:99designs/aws-vault" = "7.2.0"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:LuaLS/lua-language-server" = "3.16.0"
"aqua:ajeetdsouza/zoxide" = "0.9.8"
"aqua:alexpasmantier/television" = "0.13.12"
"aqua:astral-sh/ruff" = "0.14.8"
"aqua:astral-sh/uv" = "0.9.15"
"aqua:bootandy/dust" = "1.2.3"
"aqua:bufbuild/buf" = "1.61.0"
"aqua:cli/cli" = "2.83.1"
"aqua:dandavison/delta" = "0.18.2"
"aqua:duckdb/duckdb" = "1.4.2"
"aqua:editorconfig-checker/editorconfig-checker" = "3.6.0"
"aqua:fullstorydev/grpcurl" = "1.9.3"
"aqua:hashicorp/terraform" = "1.14.1"
"aqua:hashicorp/terraform-ls" = "0.38.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:junegunn/fzf" = "0.67.0"
"aqua:mikefarah/yq" = "4.49.2"
"aqua:mvdan/sh" = "3.12.0"
"aqua:neovim/neovim" = "0.11.5"
"aqua:pnpm/pnpm" = "10.24.0"
"aqua:rossmacarthur/sheldon" = "0.8.5"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:sharkdp/fd" = "10.3.0"
"aqua:x-motemen/ghq" = "1.8.0"

"cargo:eza" = "0.23.0"

"go:github.com/go-delve/delve/cmd/dlv" = "1.25.2"
"go:golang.org/x/tools/gopls" = "0.20.0"

"npm:@anthropic-ai/claude-code" = "2.0.58"
"npm:@biomejs/biome" = "2.3.8"
"npm:@github/copilot" = "0.0.366"
"npm:@google/gemini-cli" = "0.18.4"
"npm:@openai/codex" = "0.63.0"
"npm:pyright" = "1.1.407"
"npm:typescript-language-server" = "5.1.3"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "1.19.2"

"pipx:git+https://github.com/github/spec-kit.git" = "v0.0.89"
"pipx:snowflake-cli" = { version = "3.13.1", uvx_args = "--python 3.13.7" }
