[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[tools]
bun = "1.3.8"
deno = "2.6.7"
dotnet = "10.0.102"
go = "1.25.6"
java = "corretto-25"
node = "lts"
python = "3.14.2"
rust = "1.93.0"

1password-cli = "2.31.1"
aqua = "2.50.0"
awscli = "2.33.11"
gcloud = "520.0.0"
gradle = "8.14"
protoc = "33.4"

"aqua:99designs/aws-vault" = "7.2.0"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:LuaLS/lua-language-server" = "3.17.1"
"aqua:ajeetdsouza/zoxide" = "0.9.8"
"aqua:alexpasmantier/television" = "0.14.5"
"aqua:astral-sh/ruff" = "0.14.14"
"aqua:astral-sh/uv" = "0.9.28"
"aqua:bufbuild/buf" = "1.64.0"
"aqua:cli/cli" = "2.86.0"
"aqua:dandavison/delta" = "0.18.2"
"aqua:duckdb/duckdb" = "1.4.4"
"aqua:editorconfig-checker/editorconfig-checker" = "3.6.1"
"aqua:fullstorydev/grpcurl" = "1.9.3"
"aqua:hashicorp/terraform" = "1.14.4"
"aqua:hashicorp/terraform-ls" = "0.38.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:junegunn/fzf" = "0.67.0"
"aqua:mikefarah/yq" = "4.50.1"
"aqua:neovim/neovim" = "0.11.6"
"aqua:pnpm/pnpm" = "10.28.2"
"aqua:rossmacarthur/sheldon" = "0.8.5"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:x-motemen/ghq" = "1.8.0"

"cargo:eza" = "0.23.0"

"go:github.com/go-delve/delve/cmd/dlv" = "1.26.0"
"go:golang.org/x/tools/gopls" = "0.21.0"

"npm:@anthropic-ai/claude-code" = "2.1.23"
"npm:@biomejs/biome" = "2.3.13"
"npm:@fission-ai/openspec" = "0.23.0"
"npm:@github/copilot" = "0.0.394"
"npm:@google/gemini-cli" = "0.25.2"
"npm:@openai/codex" = "0.91.0"
"npm:pyright" = "1.1.408"
"npm:typescript-language-server" = "5.1.3"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "1.19.2"

"pipx:git+https://github.com/github/spec-kit.git" = "v0.0.90"
"pipx:snowflake-cli" = { version = "3.14.0", uvx_args = "--python 3.13.7" }
