[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[tools]
bun = "1.3.1"
deno = "2.5.6"
go = "1.25.3"
java = "corretto-25.0.0.36.2"
node = "lts"
python = "3.13.7"
rust = "1.90.0"

1password-cli = "2.31.1"
aqua = "2.50.0"
awscli = "2.31.25"
gcloud = "520.0.0"
gradle = "8.14"
protoc = "32.1"
shellcheck = "0.11.0"

"aqua:99designs/aws-vault" = "7.2.0"
"aqua:BurntSushi/ripgrep" = "14.1.1"
"aqua:LuaLS/lua-language-server" = "3.15.0"
"aqua:ajeetdsouza/zoxide" = "0.9.8"
"aqua:alexpasmantier/television" = "0.13.7"
"aqua:astral-sh/ruff" = "0.14.3"
"aqua:astral-sh/uv" = "0.9.7"
"aqua:bootandy/dust" = "1.2.3"
"aqua:bufbuild/buf" = "1.59.0"
"aqua:cli/cli" = "2.82.1"
"aqua:dandavison/delta" = "0.18.2"
"aqua:duckdb/duckdb" = "1.4.1"
"aqua:editorconfig-checker/editorconfig-checker" = "3.4.1"
"aqua:fullstorydev/grpcurl" = "1.9.3"
"aqua:hashicorp/terraform" = "1.13.4"
"aqua:hashicorp/terraform-ls" = "0.38.2"
"aqua:helix-editor/helix" = "25.01.1"
"aqua:jqlang/jq" = "1.8.1"
"aqua:junegunn/fzf" = "0.66.1"
"aqua:mikefarah/yq" = "4.48.1"
"aqua:mvdan/sh" = "3.12.0"
"aqua:neovim/neovim" = "0.11.4"
"aqua:rossmacarthur/sheldon" = "0.8.5"
"aqua:sharkdp/bat" = "0.26.0"
"aqua:sharkdp/fd" = "10.3.0"
"aqua:x-motemen/ghq" = "1.8.0"
"aqua:zellij-org/zellij" = "0.43.1"

"cargo:eza" = "0.23.0"

"go:github.com/go-delve/delve/cmd/dlv" = "1.25.2"
"go:golang.org/x/tools/gopls" = "0.20.0"

"npm:@anthropic-ai/claude-code" = "2.0.29"
"npm:@biomejs/biome" = "2.3.2"
"npm:@github/copilot" = "0.0.353"
"npm:@google/gemini-cli" = "0.11.0"
"npm:@openai/codex" = "0.50.0"
"npm:pyright" = "1.1.407"
"npm:typescript-language-server" = "5.0.1"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "1.19.2"

"pipx:git+https://github.com/github/spec-kit.git" = "v0.0.79"
"pipx:snowflake-cli" = "3.12.0"
