[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_event = 'InsertCharPre'
build = ':UpdateRemotePlugins'
depends = ['neosnippet.vim']
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  source $HOME/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_source = '''
  " Note: It must be 'imap' and 'smap'.  It uses <Plug> mappings.
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  " For conceal markers.
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
on_cmd = 'Denite'
depends = ['neomru.vim', 'neoinclude.vim']
build = ':UpdateRemotePlugins'
hook_source = '''
  source $HOME/.vim/rc/plugins/denite.rc.vim
'''
hook_add = '''
  " Prefix key
  nmap [denite] <Nop>
  map <C-j> [denite]

  " Key-mappings
  " Current directory files
  nnoremap <silent> [denite]<C-p> :<C-u>Denite file_rec -highlight-mode-insert=search<CR>
  " Buffer files
  nnoremap <silent> [denite]<C-b> :<C-u>Denite buffer -highlight-mode-insert=search<CR>
  " Outline current file
  nnoremap <silent> [denite]<C-o> :<C-u>Denite outline -highlight-mode-insert=search<CR>
  " Recent file
  nnoremap <silent> [denite]<C-r> :<C-u>Denite file_mru -highlight-mode-insert=search<CR>
  " Help tag
  nnoremap <silent> [denite]<C-h> :<C-u>Denite help -highlight-mode-insert=search<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = ['zsh']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']
depends = ['deoplete.nvim']
