# Plugin manager
[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "Shougo/vimproc.vim"

# Language Server Protocol
[[plugins]]
repo = "autozimu/LanguageClient-neovim"
rev = "next"
build = "bash install.sh"
hook_add = "call hook#add#LanguageClient#config()"

# File explorer
[[plugins]]
repo = "Shougo/defx.nvim"

# Snippets
[[plugins]]
repo = "Shougo/neosnippet-snippets"

# Quoting/Parenthesizeing
[[plugins]]
repo = "machakann/vim-sandwich"
hook_add = """
nmap s <Nop>
vmap s <Nop>
"""

# Git
[[plugins]]
repo = "lambdalisue/gina.vim"
hook_source = "call hook#source#gina#config()"

[[plugins]]
repo = "airblade/vim-gitgutter"

# Statusline/Tabline
[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = "call hook#add#lightline#config()"

# Devicons
[[plugins]]
repo = "ryanoasis/vim-devicons"

# Colorschemes
[[plugins]]
repo = "cocopon/iceberg.vim"

[[plugins]]
repo = "dracula/vim"
hook_add = "Gautocmd VimEnter * nested colorscheme dracula"

[[plugins]]
repo = "jacoborus/tender.vim"
