# Plugin manager
[[plugins]]
repo = "Shougo/dein.vim"

# Language Server Protocol
[[plugins]]
repo = "autozimu/LanguageClient-neovim"
rev = "next"
build = "bash install.sh"
hook_add = "call hook#add#LanguageClient#config()"

# File explorer
[[plugins]]
repo = "Shougo/defx.nvim"

# Snippets
[[plugins]]
repo = "Shougo/neosnippet-snippets"

# Quoting/Parenthesizeing
[[plugins]]
repo = "tpope/vim-surround"
hook_add = """
vmap S <Nop>
"""

# Git
[[plugins]]
repo = "lambdalisue/gina.vim"
hook_add = "call hook#add#gina#config()"

[[plugins]]
repo = "airblade/vim-gitgutter"

# Indent identifier
[[plugins]]
repo = "Yggdroot/indentLine"

# Statusline/Tabline
[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = "call hook#add#lightline#config()"

# Devicons
[[plugins]]
repo = "ryanoasis/vim-devicons"

# Colorschemes
[[plugins]]
repo = "cocopon/iceberg.vim"

[[plugins]]
repo = "jacoborus/tender.vim"
hook_add = "Gautocmd VimEnter * nested colorscheme tender"
