# -----------------------------------------------------------------------------
# Deoplete
# -----------------------------------------------------------------------------
[[plugins]]
repo = "Shougo/deoplete.nvim"
build = "UpdateRemotePlugins"
depends = ["context_filetype.vim"]
on_event = "InsertEnter"
hook_source = "call hook#source#deoplete#config()"

[[plugins]]
repo = "Shougo/neoinclude.vim"
on_source = ["deoplete.nvim"]

# Sources
[[plugins]]
repo = "zchee/deoplete-go"
build = "make"
depends = ["deoplete.nvim"]
on_ft = ["go"]

[[plugins]]
repo = "zchee/deoplete-jedi"
depends = ["deoplete.nvim"]
on_ft = ["python"]

[[plugins]]
repo = "zchee/deoplete-docker"
depends = ["deoplete.nvim"]
on_ft = ["dockerfile"]

[[plugins]]
repo = "zchee/deoplete-zsh"
depends = ["deoplete.nvim"]
on_ft = ["sh", "zsh"]

[[plugins]]
repo = "Shougo/neco-vim"
depends = ["deoplete.nvim"]
on_ft = ["vim"]


# -----------------------------------------------------------------------------
# Neosnippet
# -----------------------------------------------------------------------------
[[plugins]]
repo = "Shougo/neosnippet.vim"
depends = ["neosnippet-snippets", "context_filetype.vim"]
on_i = 1
hook_source = """
call hook#source#neosnippet#config()

imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
"""

[[plugins]]
repo = "Shougo/context_filetype.vim"


# -----------------------------------------------------------------------------
# Denite
# -----------------------------------------------------------------------------
[[plugins]]
repo = "Shougo/denite.nvim"
depends = ["neomru.vim"]
build = "UpdateRemotePlugins"
hook_source = "call hook#source#denite#config()"

[[plugins]]
repo = "Shougo/neomru.vim"


# -----------------------------------------------------------------------------
# Linter
# -----------------------------------------------------------------------------
[[plugins]]
repo = "w0rp/ale"
on_ft = [
  "c", "cpp", "objc", "objcpp",
  "python",
  "go",
  "dockerfile",
  "sh", "bash",
  "vim",
]
hook_source = "call hook#source#ale#config()"


# -----------------------------------------------------------------------------
# Utility
# -----------------------------------------------------------------------------
[[plugins]]
repo = "cohama/lexima.vim"
on_i = 1

[[plugins]]
repo = "tyru/caw.vim"
on_map = ["<Plug>(caw:hatpos:toggle)"]

[[plugins]]
repo = "thinca/vim-quickrun"
depends = ["vimproc.vim"]
on_cmd = "QuickRun"
hook_source = "call hook#source#quickrun#config()"

[[plugins]]
repo = "mattn/sonictemplate-vim"
on_cmd = "Template"

[[plugins]]
repo = "osyo-manga/vim-precious"
depends = ["context_filetype.vim"]
on_ft = ["markdown", "toml", "help"]
hook_add = """
let g:precious_enable_switch_CursorMoved = {"*": 0, "help": 1}
Gautocmd InsertEnter * :PreciousSwitch
Gautocmd InsertLeave * :PreciousReset
"""


# -----------------------------------------------------------------------------
# Language plugins
# -----------------------------------------------------------------------------
# Go
# [[plugins]]
# repo = "fatih/vim-go"
# on_ft = ["go"]
# hook_source = "call hook#source#go#rc()"

# Python
[[plugins]]
repo = "Vimjas/vim-python-pep8-indent"
on_ft = ["python"]

# Toml
[[plugins]]
repo = "cespare/vim-toml"
on_ft = ["toml"]
